# Generated by Django 4.0.3 on 2022-07-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room_service',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality',
            field=models.CharField(max_length=200),
        ),
    ]
