# Generated by Django 4.0.3 on 2022-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_doctor_name_alter_nurse_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_service',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
