# Generated by Django 4.0.3 on 2022-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='Patient_Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
