# Generated by Django 4.0.3 on 2022-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ambulance_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
